# Generated by Django 6.0.5 on 2026-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('fecha', models.DateField(verbose_name='Fecha del Evento')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación (Ciudad/Estado)')),
                ('activo', models.BooleanField(default=True, verbose_name='Mostrar en la web')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Calendario de Carreras',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Título de la foto')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Archivo de Imagen')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Galería de Fotos',
            },
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Patrocinador')),
                ('logo', models.ImageField(upload_to='patrocinadores/', verbose_name='Logo Oficial')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Enlace Web (Opcional)')),
                ('es_activo', models.BooleanField(default=True, verbose_name='Patrocinador Activo')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
            },
        ),
    ]
