# Generated by Django 6.0.5 on 2026-05-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriafoto',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='main_app.evento', verbose_name='Evento Asociado'),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Ej: Apoyando al equipo en cada carrera...', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='red_social_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de la Red Social'),
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='red_social_usuario',
            field=models.CharField(blank=True, help_text='Ej: @mirage', max_length=50, null=True, verbose_name='Usuario de Red Social'),
        ),
    ]
