# Generated by Django 6.0.5 on 2026-05-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_galeriafoto_evento_patrocinador_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriafoto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Aparecerá sobre la imagen al pasar el cursor.', null=True, verbose_name='Descripción breve'),
        ),
    ]
