# Generated by Django 6.0.5 on 2026-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_galeriafoto_likes_comentariofoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariofoto',
            name='reportado',
            field=models.BooleanField(default=False, verbose_name='Reportado por usuarios'),
        ),
    ]
