# Generated by Django 6.0.5 on 2026-05-25 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='patrocinadores_gustados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComentarioPatrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reportado', models.BooleanField(default=False)),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='main_app.patrocinador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeccionInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Identificador de la Sección')),
                ('likes', models.ManyToManyField(blank=True, related_name='secciones_gustadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sección Interactiva',
                'verbose_name_plural': 'Secciones Interactivas',
            },
        ),
        migrations.CreateModel(
            name='ComentarioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reportado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='main_app.seccioninteractiva')),
            ],
        ),
    ]
