# Generated by Django 6.0.5 on 2026-05-28 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_patrocinador_likes_comentariopatrocinador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriafoto',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='galeriafoto',
            name='likes',
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Baja 1000 - 2026', max_length=100, verbose_name='Título del Álbum')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Álbum')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='galeria/portadas/', verbose_name='Foto de Portada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albumes', to='main_app.evento', verbose_name='Evento Asociado (Opcional)')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes de Galería',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/fotos/', verbose_name='Fotografía')),
                ('leyenda', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pie de foto / Leyenda')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='main_app.album', verbose_name='Álbum')),
                ('likes', models.ManyToManyField(blank=True, related_name='fotos_gustadas_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fotografía',
                'verbose_name_plural': 'Fotografías',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.DeleteModel(
            name='ComentarioFoto',
        ),
        migrations.DeleteModel(
            name='GaleriaFoto',
        ),
    ]
