# Generated by Django 6.0.5 on 2026-05-28 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_galeriafoto_evento_remove_galeriafoto_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='archivo_video',
            field=models.FileField(blank=True, null=True, upload_to='galeria/videos/', verbose_name='Archivo de Video (MP4)'),
        ),
        migrations.AddField(
            model_name='fotografia',
            name='es_video',
            field=models.BooleanField(default=False, verbose_name='¿Es un video?'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/fotos/', verbose_name='Fotografía / Miniatura'),
        ),
        migrations.CreateModel(
            name='ComentarioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reportado', models.BooleanField(default=False)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='main_app.fotografia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Galería',
                'verbose_name_plural': 'Comentarios de Galería',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
