# Generated by Django 4.2.30 on 2026-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_album_id_alter_comentariofoto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('area_interes', models.CharField(max_length=50, verbose_name='Área de Interés')),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leído?')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaPatrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('puesto', models.CharField(max_length=100, verbose_name='Puesto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('organizacion', models.CharField(max_length=100, verbose_name='Organización / Empresa')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Página Web')),
                ('mensaje', models.TextField(verbose_name='Motivo de Interés')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('revisado', models.BooleanField(default=False, verbose_name='¿Revisado?')),
            ],
            options={
                'verbose_name': 'Propuesta de Patrocinio',
                'verbose_name_plural': 'Propuestas de Patrocinadores',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
