# Generated by Django 4.2.30 on 2026-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_mensajecontacto_propuestapatrocinio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Carrera'),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen Promocional'),
        ),
    ]
