# Generated by Django 4.2.30 on 2026-06-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_evento_descripcion_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores del Newsletter',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
